FROM node:18-alpine AS build

WORKDIR /app

COPY package.json package-lock.json* /app/

RUN npm install

COPY . /app

ENV VITE_CORE_API_BASE_URL=/api/v1

RUN npm run build


FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
